export const INCREMENT_REQUESTED = 'INCREMENT_REQUESTED'
export const INCREMENT = 'INCREMENT'

export const DECREMENT_REQUESTED = 'DECREMENT_REQUESTED'
export const DECREMENT = 'DECREMENT'

export const GET_GITHUB_ACCOUNT_REQUEST = 'GET_GITHUB_ACCOUNT_REQUEST'
export const GET_GITHUB_ACCOUNT_SUCCESS = 'GET_GITHUB_ACCOUNT_SUCCESS'
export const GET_GITHUB_ACCOUNT_FAILURE= 'GET_GITHUB_ACCOUNT_FAILURE'